### ISSUE TITLE
Write celery task to verify department urls resolve.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#100]
Each Department has a website attribute that needs to be verified periodically.  Write a celery task that hits a department's url and verifies the response is OK.

**Comment by Coop56** [comment]
If the task returns 200 OK I assume it should just move on and not alert anyone - but what if it returns another status code?  Should it send an email alert to someone?  Or perform some other behavior?

**Comment by garnertb** [comment]
Write the department id and url of all failures to a CSV, push the CSV to S3 and email admins a link to the failure report.
