### ISSUE TITLE
Increase quartile color contrast on bullet charts.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#11]
The breaks in the quartiles are hard to identify and would probably be indistinguishable on a projector.

<img width="263" alt="bullet-chart-legend" src="https://cloud.githubusercontent.com/assets/1141646/9384998/d8cd8df4-4721-11e5-90a4-0b090b0a5122.png">

**Comment by meilinger** [comment]
Do you have a link to an example page with this diagram?

**Comment by meilinger** [comment]
Is this still relevant?
