### ISSUE TITLE
Make service area polygon strokes thicker.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#110]
The thin outlines may be difficult to distinguish around water, when stacked and on projectors.  Make sure new implementation does not look bad though.

<img width="910" alt="screen shot 2016-03-16 at 1 52 03 pm" src="https://cloud.githubusercontent.com/assets/1141646/13823021/51e532fe-eb7e-11e5-8d57-7599e0034e24.png">

**Comment by meilinger** [comment]
Increased the weight on the stroke and re-colored to a bolder green. :+1: ?

![firestation_detail__city_of_los_angeles_fire_department_station_10](https://cloud.githubusercontent.com/assets/197163/13835061/5585cf88-ebc2-11e5-85e4-ddab088ec559.jpg)

**Comment by garnertb** [comment]
I prefer the blue, just thicker.

**Comment by meilinger** [comment]
https://github.com/FireCARES/firecares/pull/116 looks like this:

![firestation_detail__city_of_los_angeles_fire_department_station_1](https://cloud.githubusercontent.com/assets/197163/13973070/e569987e-f06c-11e5-98f6-34664158d040.jpg)
