### ISSUE TITLE
Load 2014 NFIRS data.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#124]
We have received and geocoded the 2014 NFIRS data and now it needs to be loaded into the production database.  @meilinger you wrote some scripts to do this last year, any chance could you help again this year?

**Comment by meilinger** [comment]
@garnertb Yup, but I probably can't get started until next week.  Shoot me the link to the download and i'll start pulling.

**Comment by garnertb** [comment]
This work is complete.  Running tasks to update counts and performance scores based on 2014 data now.
