### ISSUE TITLE
Fix table/row buttons responsiveness in the department list view.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#127]
At smaller browser widths, the table/row list buttons overrun the line.

<img width="671" alt="screen shot 2016-04-29 at 8 40 18 am" src="https://cloud.githubusercontent.com/assets/1141646/14916343/1fc3b49a-0de7-11e6-98c5-33be56ddb492.png">

**Comment by larskendall** [comment]
This should be fixed now.
