### ISSUE TITLE
Implement the favorite button.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#144]
The star on each department page should allow a user to toggle favoriting departments.  We should allow the user to see their favorited departments from the search page or on a similar list view.

<img width="1438" alt="screen shot 2016-06-30 at 6 34 38 am" src="https://cloud.githubusercontent.com/assets/1141646/16485464/e31a0680-3e8c-11e6-81f1-51ddd408151c.png">

**Comment by Souliloquy** [comment]
Forked django-favit: https://github.com/ProminentEdge/django-favit
Branched firecares: https://github.com/FireCARES/firecares/tree/favorite_button

Need an icon-star-full class for the UnFavorite version of the favorite button

**Comment by meilinger** [comment]
Believe that #148 fixes this
