### ISSUE TITLE
Django autocomplete fails over https.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#145]
`Mixed Content: The page at 'https://firecares.org/admin/firestation/firestation/10948/?_changelist_filters=q%3D10948' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js'. This request has been blocked; the content must be served over HTTPS.`

@meilinger: You got any cycles to check on this?

**Comment by meilinger** [comment]
Yep, I can take a look.  My cycles are few and far between at this point, but i'll dig in tonight or tomorrow.

**Comment by meilinger** [comment]
I must have accidentally pushed to the firecares upstream repo vs my fork :/  see 9ce1031bc7d3972990d53eb0d0ff900c9955a5ff and 983f78772072f4ddbe1dae2dc616429ce1a2c9b1  I wasn't able to test locally, but things should be good.

**Comment by garnertb** [comment]
All good, thanks for the fix!
