### ISSUE TITLE
Responsive Pagination not working correctly.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#146]
Notice for FDNY only 2 pages are shown (~20 stations), no arrow to click to the next set of pages.

<img width="550" alt="screen shot 2016-08-07 at 3 03 22 pm" src="https://cloud.githubusercontent.com/assets/1141646/17464590/4d4ae042-5cb0-11e6-8215-4f09961f43c4.png">

**Comment by Souliloquy** [comment]
fixed in favorite_button_rebase branch [c192ca2](https://github.com/FireCARES/firecares/commit/c192ca2ba3fc6d53d633c539cb7b382e068d48ee)

**Comment by meilinger** [comment]
fixed via 7bdf54375758582ab488508c52709fc23d6492d4
