### ISSUE TITLE
Add create signal to automatically set the region of new departments.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#150]
State to region mapping is here: https://github.com/FireCARES/firecares/blob/d7ba7ce7a4aa565850b530785c57deb78df3157e/firecares/firestation/data/nfpa-regions.csv.

**Comment by garnertb** [comment]
@HunterConnelly, want to take a shot at this one?  

Here is some documentation about signals: https://docs.djangoproject.com/en/1.10/topics/signals/.
Please include a test case.

**Comment by HunterConnelly** [comment]
Pull request #194

Sorry for the wait. This really should not have taken as long as it did.

**Comment by garnertb** [comment]
Merged
