### ISSUE TITLE
Add signal to update_performance_score upon FD creation. 

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#153]
Run this asynchronously: https://github.com/FireCARES/firecares/blob/master/firecares/tasks/update.py#L21

**Comment by garnertb** [comment]
@HunterConnelly want to take this one?

**Comment by HunterConnelly** [comment]
@garnertb I've done it, but I'm having a little trouble making a test case for it.
A default department with nothing special about it has a score of None after update_performance_score is run.
How can I confirm that this function is run upon an FD's creation when I can't tell that it's been run at all?

I thought of adding `confirmed_performance_score_updatable = models.BooleanField(default=False)` to the FireDepartment class and then adding `fd.confirmed_performance_score_updatable = True` to the end of update_performance_score, but idk if it's okay to just add stuff to the FireDepartment class.
Is this something I can do to confirm that the function was run?

**Comment by garnertb** [comment]
@HunterConnelly, This one and #152 don't lend them selves well to test coverage since they depend on a separate database that doesn't exist in development instances.  If you submit a PR that adds the signal without the test coverage, I'll merge.

**Comment by HunterConnelly** [comment]
@garnertb Added this signal and the one from #152 in pull request #195 

I wanted to use post_init to run these functions on "creation", but that resulted in lots of recursion errors, so I just used post_save. I hope that's okay.

**Comment by garnertb** [comment]
@HunterConnelly: According to the post_save docs, you can check the kwarg `created` in the receiver to tell if the instance was created or not.  If you add that in, I think its good to merge.

**Comment by HunterConnelly** [comment]
On it now

**Comment by HunterConnelly** [comment]
@garnertb done.

**Comment by garnertb** [comment]
I'm pretty sure that has to be done in the receiver vs the sender function. 

ie:

```python
if not kwargs.get('created'):
    return

# update score logic here
```

**Comment by HunterConnelly** [comment]
You're right. The docs didn't make it very clear, but looking django's source, that seems to be the way to do it.

I'll have it done in a second.

**Comment by garnertb** [comment]
Merged in https://github.com/FireCARES/firecares/pull/195.
