### ISSUE TITLE
Weird Issue with: Union Colony Fire Rescue

### ISSUE THREAD

**Issue by smesdaghi** [FireCARES/firecares#16]
Greeley CO

**Comment by meilinger** [comment]
Is this still an issue?  Assuming you're looking @ /departments/97668/union-colony-fire-rescue-authority, the geom looks a little different, but the page appears to render ok.

**Comment by garnertb** [comment]
Yes, this just means that geometry is probably wrong for the government unit.  Need to check against the Greeley Co geometry and see if we can make sense of it.

**Comment by meilinger** [comment]
When this was last visited, the department geometry matched that of the encompassing incorporated place (Nunn, Colorado)...if this is incorrect then more digging is required.  Let me know if we're good or if we need to dig further/what to look for.

![update_government_unit_associations_for_fire_department__union_colony_fire_rescue_authority](https://cloud.githubusercontent.com/assets/197163/11581095/ea05b242-9a03-11e5-8710-c1f93386322d.jpg)

**Comment by garnertb** [comment]
Looks like this is the result of an incorrect geocode of the headquarters address.  This department protects all of Greeley county.

<img width="265" alt="screen shot 2015-12-04 at 8 19 09 am" src="https://cloud.githubusercontent.com/assets/1141646/11590674/c4496560-9a5f-11e5-9c53-ee9c5f22437b.png">

* [ ] Move the headquarters geometry to the correct location
* [ ] Update the geometry with the Greeley County Geometry.
* [ ] Update the department demographic counts.
