### ISSUE TITLE
Archive Departments that aren't "Departments"

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#161]
There are some departments that have an FDID but aren't really departments. Some are just surrogates for the Fire Marshal's office. These departments should be archived -- they will still exist within firecares but the landing page will be hidden and they won't factor into any quartile ranking unless otherwise noted.

- [x] Harris County Fire & Emergency Services Department
- [x] Nassau County Fire Marshals Office
- [x] Montgomery County Fire Marshal (this is in Conroe, TX)

**Comment by cweinschenk** [comment]
Question: what do we do with PG County. There are 26 subdepartments but only one Tuxedo Cheverly has population associated with it.  Therefore should we aggregate all of these individuals into one large department (closer to reality) and then archive the individuals?

**Comment by garnertb** [comment]
These departments have been archived, as well as Division of State Fire Marshal in Tallahassee.

You can archive additional departments in slack with this command: `/firecares archive_department <department_id>`

Moving the PG County question to a new issue.
