### ISSUE TITLE
Albuquerque Fire Department

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#163]
Albuquerque does not have a community risk score. All of the information needed for the scores to be computed appear to be present. Perhaps there is an issue with FDID merge from base to risk modeling?

Don't have Risk Score:
- [x] Albuquerque
- [x] Baltimore County
- [x] Price William

**Comment by cweinschenk** [comment]
Same issue is happening with Baltimore County Department. This pings up at mostly volunteer though they have a significant number of career ffs that it could be considered most career.

**Comment by garnertb** [comment]
Albuquerque, Baltimore County and PWC don't have a predicted number of fires, an output from Stanley's model.  So we're in a holding pattern on these until we get the risk models implemented on the server side.  

Moving Colorado Springs to a new issue, since I don't think its related.

**Comment by cweinschenk** [comment]
Copy.
