### ISSUE TITLE
San Bernardino's geom is in Oklahoma

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#167]
This is odd, Headquarter's address and district geom which come from different data sets are in OK, but address is CA.

<img width="831" alt="screen shot 2016-10-24 at 12 48 56 pm" src="https://cloud.githubusercontent.com/assets/1141646/19654959/5a340c8c-99e8-11e6-9059-18e57c011b65.png">

**Comment by ssontag55** [comment]
updated boundary with census data and re-geocoded to close out issue
