### ISSUE TITLE
Low Risk Fire Counts

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#168]
Need to check to determine if the number displayed on the page is the count for low risk fires or all structure fires.

**Comment by garnertb** [comment]
Here is the query generating those counts: 
```sql
select extract(year from inc_date) as year, count(*) from buildingfires 
where fdid=%s and state=%s and extract(year from inc_date) in %s 
group by year 
order by year desc;
```

So its straight up building fires as returned in: https://github.com/FireCARES/data/blob/master/sources/nfirs/scripts/tables/building_fires.sql.  Should we update the wording from "Low Risk Structure Fires" to "Annual Structure Fires" or something?

**Comment by cweinschenk** [comment]
Yes, I think Annual Structure Fires is the better title. What are your thoughts off adding a more info hyperlink at the end of the sub header describing in more detail what we doing and some possible caveats with the data -- how some kitchen fires can get filtered out and this does not include EMS calls.

**Comment by garnertb** [comment]
More info sounds good to me, these numbers are definitely a source of confusion but its easy to articulate why they may be different from a FFs perception.

**Comment by garnertb** [comment]
@cweinschenk can you provide the help text?

**Comment by meilinger** [comment]
Wrapped up in the 1.0 release w/ low/med/high/unknown/all hazard levels.
