### ISSUE TITLE
Fix styling on favorite button for department list view

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#170]
Department list (detailed list view):
![search_for_a_community_ _firecares](https://cloud.githubusercontent.com/assets/197163/19909471/e4190074-a055-11e6-86f1-7c23e26d94bb.jpg)

Department list (card view):
<img width="270" alt="screen shot 2016-11-01 at 5 25 21 pm" src="https://cloud.githubusercontent.com/assets/197163/19909447/c4b00d68-a055-11e6-8212-1e6eca2dfcdc.png">

**Comment by cweinschenk** [comment]
@meilinger also the search only favorites needs check box needs to be fixed style wise as well as it currently wraps to the line below on the main search window.

@garnertb so I see that there is a search favorites only option -- would it be hard to add a view favorites only options just to quickly list all the departments you are following?

**Comment by cweinschenk** [comment]
Disregard check box issue.
