### ISSUE TITLE
Department boundary incorrect on refresh.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#183]
![0kdfjsbcgo](https://cloud.githubusercontent.com/assets/1141646/20391903/7725cfba-aca3-11e6-9259-a57445bc32f0.gif)

Will provide data in slack.

**Comment by meilinger** [comment]
This issue occurs when multiple polygons (not a single MultiPolygon) is used to represent a department boundary.  Ideally, we could dissolve those polygons into a single MultiPolygon before processing...
