### ISSUE TITLE
Add risk level to heatmap visualizations

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#207]
NOTE: _apply changes to `public` branch_
- Would probably be best visualized via a pie chart alongside the existing visualizations

![community_assessment__fire_department_city_of_new_york__fdny_](https://cloud.githubusercontent.com/assets/197163/21233591/56c54d36-c2b5-11e6-8fbf-3367e3cbc639.jpg)

**Comment by Souliloquy** [comment]
![screen shot 2017-01-10 at 2 14 51 pm](https://cloud.githubusercontent.com/assets/3373976/21806204/af4a829c-d740-11e6-8de2-cd96f1705998.png)

commit ea3147f
