### ISSUE TITLE
Structure risk distribution graph for parcels

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#210]
- Use D3 for visualization
- Count of structures over risk level
- Include "unknown" risk level
- Bar chart
- Tuck under the "Summary" information for the department

**Comment by garnertb** [comment]
Given the sparseness of the department boundaries and the fact that the risk models assign census tracts to departments by year vs using the jurisdictional geometry, I think the approach we should use to get parcel risk distributions is by implementing a celery task that:

1. Dissolve all census tracts "belonging" to a department by using the `nist.tract_years` materialized view.  Get the result as a WKB.

2. Use the WKB to intersect parcels and count parcels by risk level.

3. Cache that in `firedepartment.risk_models` table.
