### ISSUE TITLE
For users that are not logged-in, degrade Performance Score and Safe Grades display

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#211]
_NOTE: Apply to "public" branch_

On fire department detail pages:

- [x] Safe Grades badges should be grayed out
- [x] Add "Login to view" or similar text to badges vs actual department performance
- [x] Mention of performance regarding numbers or text "poor", "fair", etc should be replaced with link to login in content under each safe grade
- [x] Gauge on performance score should appear inactive, gray needle

![community_assessment__los_angeles_fire_department](https://cloud.githubusercontent.com/assets/197163/21268737/850b2682-c375-11e6-93df-94ef65c77a5f.jpg)

**Comment by meilinger** [comment]
@HunterConnelly you want to/have time to take a look at this one?

**Comment by HunterConnelly** [comment]
@meilinger this seems to already be done? Aside from the inactive gray needle thing, this seems like what  you described.
![screenshot](https://cloud.githubusercontent.com/assets/23296784/21394939/a07d105a-c768-11e6-8b2d-94c2f8820f46.png)

**Comment by meilinger** [comment]
@HunterConnelly It is similar; however, we'd like to have all of the components rendering (eg. the Performance Score/Safe Grades should render) BUT have any computed metrics hidden and/or replaced with either boilerplate text or a link: "Login to view".  The idea was to keep the badges on the Safe Grades in place, but with a gray background and directional text to tell the user to login to view this information.  Similarly, the Performance Score needle would need to be gray/gradient gauge would be gray and numbers would be removed.  In the text under each safe grade, mentions of performance (eg. "This department's performance score is _poor_") would need to replaced with an inline link to login => "The department's performance score is [LOGIN TO VIEW]".  The inline text might be overwhelmed with links in this case, so we might need another strategy if the [LOGIN TO VIEW] replacement looks odd.

**Comment by HunterConnelly** [comment]
@meilinger is this what you want it to look like?
![screenshot](https://cloud.githubusercontent.com/assets/23296784/21404417/1dc3c664-c78f-11e6-90ba-a6644cec782b.png)

**Comment by meilinger** [comment]
@HunterConnelly looks pretty close!  Maybe try making the gradient gray, removing the numbers from the performance score, removing the question mark from the gauge and then have the needle point straight up.  @garnertb @lizhodges, what do you think?

**Comment by cweinschenk** [comment]
I agree with @meilinger

**Comment by garnertb** [comment]
@meilinger agreed.  I think the needle should either be pointing up (90 deg) or at the very bottom of the gauge to the left, may take a couple of iterations to get perfect.

**Comment by HunterConnelly** [comment]
The needle is the easy part. Straight up is 0 deg, down is 180. I set it to point down to indicate that it's not giving the actual value (or, alternatively, to point to the "please login" text).

The hard part is setting the gradient to be gray, as I can't use django template tags in CSS files. Instead I'll have to create a custom class for the disabled gauge and set its gradient colors using CSS.

I can't do it tonight though. I'll be sure to finish this tomorrow.

**Comment by meilinger** [comment]
Ideally, we'd set a "disabled" class on the parent element of the gauge OR add a "disabled" attribute to the gauge, which would then be pulled into to the scope of the gauge directive and would toggle a "disabled" class on the root element of the rendered directive.  CSS would be able to do its magic on rendering the inherited styling correctly after a `.gauge.disabled` (or `.disabled .gauge` in the former case) background style was set.

**Comment by HunterConnelly** [comment]
How's this one?

![screenshot](https://cloud.githubusercontent.com/assets/23296784/21446611/4bdc8d94-c896-11e6-9ae5-9607d9a96958.png)

**Comment by lizhodges** [comment]
So, I think its clean.. I'm wondering what it's telling me =)  Is it grey
because they are not available but the colors would match the key if they
were available?

**Comment by meilinger** [comment]
@lizhodges yep, exactly

**Comment by meilinger** [comment]
@HunterConnelly could you submit a PR for this when you get a sec (I _think_ you had wrapped things up)?

**Comment by meilinger** [comment]
see 2f7565117434b3907d0333f470fac128ea73f048
