### ISSUE TITLE
Add ability for a department administrator to revoke sent invites

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#212]
_NOTE: apply to "public" branch_

On a department user administration page (eg. /departments/87256/settings/users), allow for unaccepted sent invitations to be revoked.

![update_user_associations_for_fire_department__los_angeles_fire_department](https://cloud.githubusercontent.com/assets/197163/21269301/ce221be4-c377-11e6-8234-241b9628fb9d.jpg)

**Comment by meilinger** [comment]
@HunterConnelly you have a few cycles for this one?

**Comment by istodi** [comment]
Feature created on #271
