### ISSUE TITLE
Department data upload matching modifications

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#218]
When uploading a set of firestations via the department's "Update data" function (on the department detail page) the upload procedure should search for an existing station by ID and then by name + associated department when doing an update.  If id is empty or 0, then insert the station, otherwise find the station by id _or_ name + department and update.

**Comment by meilinger** [comment]
@HunterConnelly you have a few to take a look at this next?

**Comment by garnertb** [comment]
@HunterConnelly there is test coverage of the upload functionality in which you should be able to reproduce this: https://github.com/FireCARES/firecares/blob/master/firecares/firestation/tests.py#L955

**Comment by meilinger** [comment]
see `firecares.importers.GeoDjangoImporter`

**Comment by meilinger** [comment]
see #357

**Comment by meilinger** [comment]
Wrapped this up while fixing #357
