### ISSUE TITLE
Search Function on Population

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#222]
If you toggle the search criteria slider for population and slide the lower side or upper side -- the search function works properly in that it filters the departments. The problem is that FDNY is always dropped from the search even it the upper bound is set to max. We go from 27,162 to 27,161 searchable departments. My guess this has to do with the population of NYC being higher or equal to the bound on the slider. The DIST score search works properly - the max shows up (at least it seems to). Also - should be change the text from DIST to performance score?

**Comment by cweinschenk** [comment]
For the DIST and Population sliders, should the labels go above to be consistent with all of other features. It gets confusing down at the bottom.

**Comment by meilinger** [comment]
@Souliloquy want to take a look at this next?  This can be done in a branch based off `master` and then submitted as a pull request since we'll merge this into production.

**Comment by meilinger** [comment]
@Souliloquy Looks like the `protected population` slider is at fault on this.  Even when I move the handle to the max for this field, it doesn't get set to the actual max.

**Comment by Souliloquy** [comment]
Fixed it on a branch called Search_Population_222 commit 595ac61

**Comment by meilinger** [comment]
@Souliloquy we might also want to change the labels for the sliders to be above the slider control itself as per @cweinschenk's comment, this will also mean that the popover needs to be set to display below the slider.

**Comment by Souliloquy** [comment]
I tried it with the popover above the slider, see if you like it. 	e47642c

**Comment by Souliloquy** [comment]
![screen shot 2017-01-31 at 4 37 41 pm](https://cloud.githubusercontent.com/assets/3373976/22469151/ada5e726-e7d3-11e6-80ff-c110cf12df1d.png)

**Comment by Souliloquy** [comment]
![screen shot 2017-01-31 at 4 39 32 pm](https://cloud.githubusercontent.com/assets/3373976/22469219/f0129802-e7d3-11e6-9112-7c4b6424b75c.png)

**Comment by meilinger** [comment]
see 8c38bfa7af6847042470a6113a5dd5ea1916b680

**Comment by meilinger** [comment]
nice work, @Souliloquy !
