### ISSUE TITLE
Fix database issue when running single unit tests

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#236]
Getting this on the first database access when running a single unit test OR if the first unit test run tries to create/update objects in the `FireDepartment` model.

```
DataError: invalid input syntax for integer: "f"
CONTEXT:  PL/pgSQL function department_fts_document(firestation_firedepartment) while storing call arguments into local variables
PL/pgSQL function department_fts_document_trigger() line 4 at assignment
```

**Comment by garnertb** [comment]
This should have been fixed in 251d6500e8a5406cfc16c3a8b92a8f9d28d5a308.

**Comment by meilinger** [comment]
Tyler has a solution for this, root cause was fire department schema changes AFTER the trigger was created, causing parameter mismatches.

**Comment by meilinger** [comment]
verified, closing
