### ISSUE TITLE
Strategy for handling N/A hazard levels in FireCARES

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#243]
Determine if parcels with the N/A hazard level should:

- Be included as a distinct and separate hazard risk level (eg. filterable on specific fire department detail pages) and included in the "All levels" aggregation, we would have 5 "levels" at this point: `all`, `low`, `medium`, `high`, `n/a` OR
- Be included within "All levels", but not segmented out as a distinct level to filter on

There are pros and cons to both approaches, but we need a decision to work against in handling N/As.  This issue is mainly meant as a transparent conversation log with eventual decision and path forward upon closing.

**Comment by garnertb** [comment]
Discussed this on 1/30 telcon, decision was to implement N/As in a new levle called "Unknown".
