### ISSUE TITLE
Do not show empty structure count graph when there is not structure count histogram.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#254]
We should either 1) not show the graph at all, or 2) show it in a 'disabled' state.

![image](https://cloud.githubusercontent.com/assets/1141646/22738337/00031e24-edd5-11e6-81fc-32e9d73f34bd.png)

**Comment by meilinger** [comment]
fixed in deed7166703131988c4575be08a521b64b1c6c0a (hidden for now)
