### ISSUE TITLE
Structure Risk Distribution graph changes

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#259]
_NOTE: apply to the `public` branch_

Appears to be floating out on its own right now.

- Keep in the same location
- Switch background color to resemble that of the "Safe Grades" section
- Make header same size as the other headings on the page (eg. "Summary", "Description", etc)
- Change header to "Structure Hazard Level Distribution"

**Comment by meilinger** [comment]
@cweinschenk was thinking of something along the line of the following to make the structure type graph stick out, matches the style of the "Safe Grades" cards...what do you think?

![community_assessment__los_angeles_fire_department](https://cloud.githubusercontent.com/assets/197163/22944980/31850af6-f2b8-11e6-800a-5d737f543f51.jpg)

**Comment by cweinschenk** [comment]
@meilinger  this is exactly what I was thinking! 

Here is another question for you -- is there a way to show an approximate number of structures on top of the bars or something -- like low risk structures ~720k and medium ~320k as it is hard to know those numbers from that chart -- or maybe on hover over?

**Comment by meilinger** [comment]
Yeah, i was thinking the same thing...a tooltip on hover would fit nicely.

**Comment by meilinger** [comment]
![community_assessment__los_angeles_fire_department](https://cloud.githubusercontent.com/assets/197163/22980321/acb1a562-f35e-11e6-96ef-36c8c658d747.jpg)

**Comment by cweinschenk** [comment]
I really like this!
