### ISSUE TITLE
Data feedback form

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#260]
_NOTE: apply to `public` branch_

On a per-department/station level, we need to capture requests for data modification/feedback:

- Create a `DataFeedback` model and form that captures:
    - The requesting user's information
    - The department or fire station that the request is about
- Requires a user to be logged into FireCARES
- Look into reusing components of the `AccountRequest` or `ContactUs` workflows/templates/forms/models
- Unit test

**Comment by istodi** [comment]
Check it out in #270 it's an angular directive in which you need to pass some arguments for example:

```
{% if user.is_authenticated %}
    <feedback
        url="{%url 'firedeparment_data_feedback_slug' object.id object.slug %}"
        user="{{ user.id }}""
        firedepartment="{{ object.id }}"
        firestation=""
        csrftoken="{{ csrf_token }}"
    >
        <i class="fa fa-envelope-o fa-2x"></i>
    </feedback>
{% endif %}
```

The directive have transclusion so you can pass any icon or text to build the link.

I can put the urls in templates, any suggestion of places and UI to show?

**Comment by meilinger** [comment]
Put an instance close to the map on the department and station detail pages and one in the header alongside the other icons (print, favorite, etc).

**Comment by istodi** [comment]
Done, two links per detail page of fire station and fire department, one on the header, and the other above the map.

**Comment by meilinger** [comment]
👍
