### ISSUE TITLE
Include total protected structures for department

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#268]
_NOTE: apply to `public` branch_

- Either under the "Structure Hazard Level Distribution" graph OR
- Under the "Summary" section OR
- As an item (w/ icon) under the "Description" section
- Total count can be pulled by summing the count of low/medium/high and unknown structure counts (used in rendering the "Structure Hazard Level Distribution" graph)

**Comment by meilinger** [comment]
Going with this to start...

![community_assessment__los_angeles_fire_department](https://cloud.githubusercontent.com/assets/197163/23080470/6e1840c2-f516-11e6-9102-b4166b0c12ce.jpg)

**Comment by cweinschenk** [comment]
@meilinger this is perfect for initial roll out. Looks great! Nice work.
