### ISSUE TITLE
Create view to update linked government unit for each department.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#28]
FireCARES needs a view for users to update the government units that are linked to each fire department.

* [x] Only users with update perms on FireDepartment objects should be allowed to access the view.
* [x] View should have a map with a checkbox for each government unit type that intersects the department's headquarters location including: County, Incorporated Places, Minor Civil divisions, Native American Areas, Reserves, and Unincorporated Areas.  If the check box is selected the geometry will be included as a linked government unit.  
* [x] View should should show pertinent information about each intersecting government unit geometry including FIPS code, population, name.
* [x] View should should show pertinent information about the selected fire department.
* [x] View should optionally allow the user to update the department's geometry based on the selected government units.
* [x] Because changing a government unit could potentially alter the population class, the PopulationClassQuartile materialized views will need to be refreshed (via celery).
* [x] Url Route should be: ```/departments/<id>/settings/government-unit```
* [x] Include unit tests ensuring at authorization and the functional capabilities.

**Comment by meilinger** [comment]
Should the map include the government units (in addition to the department geom + headquarters)?

**Comment by garnertb** [comment]
I was thinking thinking of having separate maps vertically for each government unit object that intersects the geom.  The government unit's geometry would be included on the map.

**Comment by meilinger** [comment]
Makes sense.

**Comment by meilinger** [comment]
I'm assuming that the protected population should be recalculated whenever the government unit associations change, should that be the case?  Also, a union of MultiPolygons that overlap doesn't produce a single contiguous polygon (which makes sense) and instead produces two separate polygons...should I attempt to simplify a multipolygon to single poly before performing the union?

**Comment by garnertb** [comment]
1) Correct.
2) Just create a multipolygon from the list of polygons without modifying any of the geometries, unless you have a reason/example why that would be a bad idea?
