### ISSUE TITLE
Make "Learn more" more prominent on the department detail page

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#288]
_NOTE: apply to `public`_

- Move "Learn more" text to directly below the "Safe Grades", increase font size
- Use either a question icon or move the "Learn more" links on the community assessment to the heading

**Comment by istodi** [comment]
Some design proposals:

Community assessment

tooltip hidden            |  tooltip showing
:-------------------------:|:-------------------------:
![community](https://cloud.githubusercontent.com/assets/74675/23520297/f7345516-ff3f-11e6-96e3-30c6247450df.png) | ![community_tooltip](https://cloud.githubusercontent.com/assets/74675/23520624/70724ea0-ff41-11e6-8b0c-07fe1e51e433.png)

Safe grades

tooltip hidden            |  tooltip showing
:-------------------------:|:-------------------------:
![safegrades](https://cloud.githubusercontent.com/assets/74675/23520508/f21ff7c8-ff40-11e6-83f1-341c7305cc2a.png) |  ![safegrades_tooltio](https://cloud.githubusercontent.com/assets/74675/23520622/6c66a356-ff41-11e6-9c30-675305705439.png)


The tooltip is enabled on mouse hover, but can be inactive and only use the icon alone.

@cweinschenk, @meilinger, let me know what you think.

**Comment by cweinschenk** [comment]
I like the hover over and the Icon. It becomes consistent throughout the site then too. I think I like the right align best style wise but it may be more functional when it is inline near the score header.

**Comment by istodi** [comment]
@cweinschenk in the header of the performance score, like this?
![captura de pantalla 2017-03-02 a la s 12 29 59](https://cloud.githubusercontent.com/assets/74675/23521296/00a8b106-ff44-11e6-8d10-b2697fff2501.png) 
and for the community assessment can be closer too.
![captura de pantalla 2017-03-02 a la s 12 31 36](https://cloud.githubusercontent.com/assets/74675/23521359/3e0f002c-ff44-11e6-8ae2-e53b5a3501dc.png)

**Comment by istodi** [comment]
nevermind, performance score and safe grades need their own "learn more", anyway, performance score can have the same "learn more" link as the other parts.

**Comment by meilinger** [comment]
@cweinschenk cool if we go w/ the left-aligned icon version for the "Community Assessment" and "Safe Grades" to start?

**Comment by meilinger** [comment]
Thanks @istodi !
