### ISSUE TITLE
Identify departments with poor parcel coverage

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#289]
- Using census tract-based jurisdiction in combination with parcels in the aforementioned area should give us a good benchmark for the quality of the structure distribution as well as other metrics on the page

**Comment by garnertb** [comment]
This is a blocker for me in order to reach out the parcel vendor.

**Comment by meilinger** [comment]
Working this one right now.

**Comment by meilinger** [comment]
emailed the initial analysis using structure counts vs population by department, waiting for the coverage % by census tract-based jurisdictions vs parcel coverage by department

**Comment by meilinger** [comment]
see https://github.com/FireCARES/data/blob/master/sources/parcels/notebooks/structure-count-vs-population.ipynb

**Comment by meilinger** [comment]
Top offenders for low parcels using structure counts:

|     |    id | name                                                                    | state   |   population |   structure_count |   people_per_structure |
|----:|------:|:------------------------------------------------------------------------|:--------|-------------:|------------------:|-----------------------:|
|  18 | 91907 | Philadelphia Fire Department                                            | PA      |      1526006 |    1845           |              827.104   |
|  20 | 95982 | St. Lucie County Fire Distrtict                                         | FL      |       277789 |     377           |              736.841   |
|  43 | 97554 | Tuxedo Cheverly Fire Department (Prince Georges County Fire Department) | MD      |       863420 |    3709           |              232.791   |
|  49 | 77326 | Chesapeake Fire Department                                              | VA      |       222209 |    1693           |              131.252   |
|  52 | 77866 | City of San Bernardino Fire Department                                  | CA      |       209924 |    1987           |              105.649   |
|  53 | 77530 | Citrus Sheriff Fire Rescue                                              | FL      |       141236 |    1339           |              105.479   |
|  58 | 98629 | Waterbury Fire Department                                               | CT      |       110366 |    2184           |               50.5339  |
|  59 | 86024 | Lafayette Fire Department                                               | LA      |       120623 |    2483           |               48.5795  |
|  61 | 85736 | King County Fire District 40                                            | WA      |       591873 |   13590           |               43.5521  |
|  63 | 75742 | Bridgeport Fire Department                                              | CT      |       144229 |    3334           |               43.26    |
|  64 | 91590 | Paterson Fire Department                                                | NJ      |       146199 |    3603           |               40.577   |
|  70 | 84592 | Howard County Fire & Rescue                                             | MD      |       287085 |   11575           |               24.8022  |
|  75 | 97304 | Travis County Fire Rescue                                               | TX      |       233876 |   12508           |               18.6981  |
|  76 | 94288 | San Mateo County Fire Department                                        | CA      |       209418 |   11243           |               18.6265  |
|  79 | 98964 | West County EMS & Fire Protection District                              | MO      |       439658 |   28416           |               15.4722  |
|  81 | 86743 | Lexington Fire Department                                               | KY      |       295803 |   21393           |               13.8271  |
|  83 | 77049 | Central Jackson County Fire Protection District                         | MO      |       400042 |   29304           |               13.6514  |
|  84 | 91969 | Pierce County Fire District Number 3 dba West Pierce Fire & Rescue      | WA      |       484613 |   36013           |               13.4566  |
|  86 | 77992 | Clark County Fire District 6                                            | WA      |       396218 |   30114           |               13.1573  |
|  92 | 86911 | Linden-Peters Rural County Fire Protection District                     | CA      |       155612 |   14557           |               10.6898  |
|  94 | 89562 | Murrieta Fire Department                                                | CA      |       103466 |   10061           |               10.2839  |
|  95 | 73375 | Alexandria Fire Department                                              | VA      |       279932 |   28275           |                9.90034 |
| 105 | 74897 | Bernalillo County Fire & Rescue                                         | NM      |       662564 |   85213           |                7.77539 |
| 106 | 90282 | North Ada County Fire & Rescue District                                 | ID      |       105809 |   13635           |                7.7601  |
| 109 | 81472 | Fire Department City of New York (FDNY)                                 | NY      |      8175133 |       1.11738e+06 |                7.31633 |
| 117 | 74241 | Bakersfield Fire Department                                             | CA      |       347483 |   57322           |                6.06195 |
| 120 | 83733 | Hartford Fire Department                                                | CT      |       124775 |   21721           |                5.74444 |
| 126 | 94379 | Santa Ana Fire Department                                               | CA      |       324528 |   59766           |                5.42998 |
| 127 | 76429 | Cambridge Fire Department                                               | MA      |       105162 |   19459           |                5.40429 |
| 128 | 80667 | Elizabeth Fire Department                                               | NJ      |       124969 |   23766           |                5.25831 |

**Comment by meilinger** [comment]
By parcel coverage of the census tract-based department jurisdiction, the 3 departments that are less than 15% coverage (and are considered featured departments) are:

91907 - Philadelphia Fire Department, PA (~3% coverage)
80595 - El Paso Fire Department, TX (~14% coverage)
95982 - St. Lucie County Fire Distrtict, FL (~14% coverage)

![u9tmlbeuddozrljqzcws4ui3m0uec93mlbeuddozrljqzcws8f8ajnluffhktmgaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/197163/23480333/391eee54-fe8d-11e6-86ee-a3310586fe0a.png)

**Comment by meilinger** [comment]
El Paso actually doesn't look to bad in terms of parcel coverage, issue is a huge area is considered part of the census tract-based jurisdiction (outlined in red):

![parcel-coverage-for-departments](https://cloud.githubusercontent.com/assets/197163/23482061/542a52f0-fe93-11e6-95e1-0c5b254854b5.jpg)

**Comment by garnertb** [comment]
Closing, I think we're good here.
