### ISSUE TITLE
create_quartile_views function should not drop materialized views by default.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#337]
This logic should be switched to do a `REFRESH MATERIALIZED VIEW` to prevent concurrent lookups from throwing exceptions.

https://github.com/FireCARES/firecares/blob/public/firecares/firestation/models.py#L1155

**Comment by meilinger** [comment]
see 5a9069c1cd81454dfc84e75035419fa7c8258c1f

**Comment by meilinger** [comment]
Deployed.  When we upgrade to Postgres 9.4+, we should use `CONCURRENTLY` if we want to prevent blocking scans.  Currently, regenerating the view will block scans.
