### ISSUE TITLE
On department save, update covered population via census tracts if jurisdiction changed

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#349]
Using 100% of tract populations for tracts that are wholly covered by the department jurisdiction and appropriate percentages based on tract coverage for tracts that are partially contained.  This method isn't 100% accurate since it assumes a uniform population density across the tract, but should be close.

**Comment by cweinschenk** [comment]
This works for me. We can also confirm with local department as they tend to have that information as well. Can we provide a way to put preference on a manual override?

**Comment by meilinger** [comment]
Yes adding a flag for manual override would be preferable as that information is probably more accurate.

**Comment by ssontag55** [comment]
We'll have to do this asyn because it can take a little while to update

**Comment by meilinger** [comment]
@ssontag55 is this wrapped up?

**Comment by ssontag55** [comment]
@meilinger Still waiting to push this
