### ISSUE TITLE
Stand up mapzen instance for geocoding incoming incidentaddresses

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#356]

**Comment by meilinger** [comment]
OBE at this point due to low rooftop hit rates per MapZen analysis, @istodi could you include your analysis notebook in this issue?

**Comment by istodi** [comment]
Analysis included in scripts/mapzen_analysis through 01e7997

**Comment by meilinger** [comment]
@istodi , perfect!  thanks!
