### ISSUE TITLE
Update mobile links.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#36]
The mobile links (which are only displayed with smaller viewports) are incorrect.  These need to be updated with the actual FireCARES urls.

Content is in: `<nav class="ct-menuMobile">`

**Comment by meilinger** [comment]
@wgb Let me know if you want me to grab this, didn't want to step on your toes if you were actively working it.

**Comment by garnertb** [comment]
@meilinger, you're free to work this.  @wgb is supporting another project for the foreseeable future.

**Comment by Coop56** [comment]
I have time to work on this today - are you still working on this @meilinger?

**Comment by meilinger** [comment]
@Coop56 Go for it!

**Comment by Coop56** [comment]
Just finished this up.  I created a new file to make managing the mobile navbar links easier.  _mobile_navbar.html and I included this on all of the pages that previously had a hard coded mobile navbar.  I'm running the unit tests now and then I'll push my changes.
