### ISSUE TITLE
Implement a sitemap.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#37]
Use the Django sitemaps module: https://docs.djangoproject.com/en/1.8/ref/contrib/sitemaps

**Comment by garnertb** [comment]
@sbaxter, what is the status of cb7c4d0?

**Comment by sbaxter** [comment]
It contains a sitemap with the login and the home page. I was planning on querying the database to construct a dynamic list of all available pages, but haven't had time yet :)

**Comment by Coop56** [comment]
@sbaxter Are you still working on this?  If you're busy elsewhere I'll be happy to pick it up.

**Comment by sbaxter** [comment]
Go for it!
