### ISSUE TITLE
Display weather risks for a department

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#371]
- Department detail pages should display an indicator of current warnings
- @lizhodges probably has some good ideas on how to update the department detail page to encompass this functionality
- Requires harvested department-level hazards before implementation (see #369 and #370)

**Comment by meilinger** [comment]
@ssontag55 we also need to hide the weather warnings layer after we get to the zoom point that the parcels start to display in order to prevent obscuring parcel colors, @bingles also has a comp coming for the display of the weather warning message box

**Comment by bingles** [comment]
Hey @ssontag55 and @meilinger, attached is the weather warning comp. Changed the style around a little to better fit the overall visual design. Let me know if there are any issues with the proposed design...happy to discuss! 

Also, I realize this might have implications on the existing user notification system design, in which I can provide additional notification styles for other situations (ie. Help, Alert, Error, Success).

![weather_advisory_warning](https://user-images.githubusercontent.com/636170/31201477-cde38a0a-a92c-11e7-82e3-30adb7f20337.png)

**Comment by bingles** [comment]
Hey @ssontag55, here is the Codepen that contains the various notification types and less/css styles: [codepen.io/bingles/pen/zEpOZV](https://codepen.io/bingles/pen/zEpOZV). Its pulling base Bootstrap 3.3.5 styles and modifying. Let me know when you cycle back on to this and I can explain if needed!

**Comment by ssontag55** [comment]
thanks @bingles , should be all set @meilinger
