### ISSUE TITLE
Update Annual Structure Fire Range Graphs

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#380]
Currently, the callout for annual structure fires is leading to confusion for users. The proposed change would change it from a national call out to a local call out.

The first column would remain the same. The second column would be titled Structure Fires (the backend infrastructure would stay the same). The third column would change. Instead of looking at national data, the max for each year would be the total count of fires as reported in NFIRS each year for the given fire department. The caret would then scale based on the number of structures fires (column 2). This would highlight two issues within the data: 1. if the total fires in NFIRS changes drastically each year it would indicate the department is missing records) 2. if the percentage of structure fires changes dramatically then the department has a reporting issue

Ultimately we would want to build in functionally with a drop down like for the hazard level functionality to be able to update this slider to filter on total calls (including ems) once that data is acquired.

**Comment by meilinger** [comment]
- [ ] Rename second column to **Structure Fires**
- [ ] Use **local** fire department fires over all available years (min/max) for the start/end of the **Call Volume** slider

**Comment by meilinger** [comment]
So basically, we'd have min/max, per hazard level (Low/Med/High/Unknown/All) akin to the image below:

<img width="581" alt="community_assessment__los_angeles_county_fire_department" src="https://user-images.githubusercontent.com/197163/30753338-aaef52c4-9f84-11e7-907a-e43026ec6c4f.png">

@cweinschenk does that make sense?

**Comment by cweinschenk** [comment]
I was thinking something a little different. Each year would have a unique max based on the unfiltered total of fire calls we have from NFIRS -- the 1396 is filtered based on the calls that are structure fires --- what the slider should be showing is essentially percentage of fire calls that are structure fires. The end number should probably change year to year.

**Comment by meilinger** [comment]
Ah, ok.  So across _all_ call types, that's what i was missing.  Display the proportion of structure fire calls vs _total_ calls for each year.  Was doing the proportion of this year vs the rest for _only_ structure fire calls in the image above.

**Comment by cweinschenk** [comment]
Well _all_ fire call types. We don't have _non_ fire call data yet. That is what is tripping users up. When we say call volume, that is typically in reference to the sum of all calls they run -- fire, ems, haz mat, accidents, rescue, etc. We only have fire calls from NFIRS at the moment I believe.

**Comment by meilinger** [comment]
Further-updated the column names, but using structure fires as a subset of fire-related calls:

<img width="596" alt="community_assessment__township_of_union_fire_department" src="https://user-images.githubusercontent.com/197163/30828648-f2839ed4-a203-11e7-9bad-56e2c2e2c2d9.png">
