### ISSUE TITLE
Prevent clickjacking with X-Frame-Options.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#39]
Set the X-Frame-Options header to SAMEORIGIN:

Implementation in nginx is preferred:  https://gist.github.com/plentz/6737338#file-nginx-conf-L10

But implementation in Django is also acceptable: https://docs.djangoproject.com/en/1.8/ref/clickjacking/#setting-x-frame-options-for-all-responses

**Comment by sbaxter** [comment]
https://github.com/FireCARES/firecares-ansible/pull/2

Not sure how y'all like to test things like this; in case you want to include it in the python suite:
```
def test_x_frame(self):
    """
    Ensure same origin policy to prevent clickjacking
    """
    c = Client()
    response = c.get(reverse('robots.txt'))
    self.assertEqual(response['X-Frame-Options'], 'SAMEORIGIN')
```

**Comment by garnertb** [comment]
In general, I like to include tests for everything to prevent regressions, but the python test suite is currently running in the django test server which does not send requests through nginx so this would fail.  I'm ok without the test for this until we can get a more robust test suite.  Thanks!
