### ISSUE TITLE
Display on the Department page the # of firefighters able to respond to parcels

### ISSUE THREAD

**Issue by ssontag55** [FireCARES/firecares#396]
Use a table or other textual display to list the metadata from the response time analysis showing the number of firefighters and time able to response in addition to the number of parcels for each risk level (high, medium, low, unknown)

**Comment by meilinger** [comment]
<img width="932" alt="community_assessment__los_angeles_county_fire_department" src="https://user-images.githubusercontent.com/197163/31964467-b5a1fb78-b8c9-11e7-9610-be2562cf76b1.png">

We should probably keep the parcel coloring graph consistent w/ the rendering of the parcels/risk levels.  "Low" = green, "Medium" = orange, "High" = red and "Unknown" = gray (akin to the Community Risk levels).

**Comment by ssontag55** [comment]
![screenshot from 2017-10-25 14-43-48](https://user-images.githubusercontent.com/563334/32016878-098b9a5e-b993-11e7-8acd-fc84c444ce4b.png)

**Comment by cweinschenk** [comment]
This is sick...do you have this stood up anywhere where I can play around with it?

**Comment by ssontag55** [comment]
Adjusting a couple color palettes first.  Soon!
