### ISSUE TITLE
De-normalize Country from the Address model.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#4]
In some views (IE the admin section) the Country lookup seems to be executing for every address record.  Every record on the Address table is currently in the US, so it seems logical to just remove the foreign key and replace it with a string directly on the Address model.

**Comment by acengic** [comment]
Tyler, 
Can you please include url to recreate the issue whenever it’s possible. It saves time on my side.
Thanks,
Arif

**Comment by meilinger** [comment]
Denormalization had very little effect on the load time since the select_related was being used in the ModelForm for addresses.  However, the page was still taking quite awhile to load due to the size of the related fields rendering in `<select>` widgets.  Django-autocomplete-light does the trick.

**Comment by meilinger** [comment]
Reverted the denormalization.

**Comment by garnertb** [comment]
Is this good to merge?  Was it supposed to be a PR?

**Comment by meilinger** [comment]
Yep, just pushed up, making sure things are good before I submit a PR.

**Comment by garnertb** [comment]
Merged in d7b0bbe4cdc277ee34a9533542d9791b97215fa7.
