### ISSUE TITLE
Tile View Data

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#407]
The number showing in tile view for the predicted number of fires does not align with the number shown in the prediction table on the department page.

**Comment by meilinger** [comment]
Predicted:

<img width="405" alt="banners_and_alerts_and_community_assessment__houston_fire_department" src="https://user-images.githubusercontent.com/197163/33327151-6c90254a-d41c-11e7-9a85-d90289a35fd4.png">

Not displaying correct # on department list view:

<img width="300" alt="search_for_a_community_ _firecares" src="https://user-images.githubusercontent.com/197163/33327244-a129e174-d41c-11e7-838f-a5885d8896c1.png">

**Comment by cweinschenk** [comment]
@joe -- a secondary and perhaps larger problem is that the 1135 is a better prediction compared to that 4k+ number. I think we might need to figure out what changed on Stanley's end because 4k is just nonsense when the average was 1k.

**Comment by meilinger** [comment]
For clarity, we:

- Need to determine which number is the actual truth from provided predictions
- Update either the list view or the detail page to match

**Comment by meilinger** [comment]
Verified that the correct predictions are indeed in the department detail page...switched department list view to use the # of predicted fires for "All" structure hazard levels.
