### ISSUE TITLE
Weather Warning Notifications

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#413]
Currently the weather notifications on the test site are functional but the notification window takes up too much real estate. If we think in terms of rack equipment — perhaps make the warning 2U high  — 1U for indicated that warnings exists, and 1 U for a click to expand that allows the user to see all of the warnings.

**Comment by meilinger** [comment]
This has been pushed to test.firecares.org.  https://test.firecares.org/departments/77379/chicago-fire-department

**Comment by cweinschenk** [comment]
I like this update.

Do we have a writeup anywhere describing what we are doing for this: how far from a department do we pull warnings for or is just any intersection, is everything colored red, what is the warning list that we are using, etc -- this could be in bullet form -- I can write it up for users as I think it would useful.

**Comment by meilinger** [comment]
@cweinschenk there's a bit of a write-up on the original milestone => https://github.com/FireCARES/firecares/milestone/5

- It's considered a warning for the department based on an intersection w/ the department's jurisdiction
- Warnings come from NOAA
- All of the warnings (regardless of type of warning) are colored red on the map

**Comment by cweinschenk** [comment]
Perfect. I will start with that.

**Comment by cweinschenk** [comment]
I added myself for the writeup portion of this.

**Comment by ssontag55** [comment]
Also, warnings can be updated based on region and or parameters of the  warning. Warnings are removed from the page if the time is past the expired datetime.  Warnings are archived in the database.

**Comment by cweinschenk** [comment]
We are archiving so we can back and check to see if warning overlay with spikes in calls, etc? If yes, bad ass!

**Comment by ssontag55** [comment]
Yep, do further analysis.
