### ISSUE TITLE
Re-add the fire station view.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#42]
* [x] Should look similar to the department view, but map is centered on the station location.
* [x] Route should be: `/stations/<id>/<slug>?`
* [x] Include staffing module developed in the older version of the application (https://github.com/FireCARES/firecares/blob/master/firecares/firestation/static/firestation/firestation.js#L97)
* [x] Here is the old template that needs to be updated: https://github.com/garnertb/rogue_geonode/blob/response-capability-form/geoshape/firestation/templates/firestation/firestation_detail.html
* [x] Needs to be done by 11/20.

**Comment by meilinger** [comment]
* [ ] Basic access unit tests
