### ISSUE TITLE
Effective Response Force layer colorization 

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#424]
We need to figure out a way to better discern between low/med/high/unknown layers.  Create a few alternatives and attach screenshots to this issue for review:

- Use borders on layers
- Stronger color separation between med/high layer colors
- Remove "unknown" layer from map as it is gray and could be washing out the other hazard level colors

**Comment by ssontag55** [comment]
@meilinger @bingles a couple ideas for highlighting areas have a tooltip on hover.  Removing Opacity hides other map elements but really brings the colors out more and matches the graph.  When setting opacity (.4) colors get drowned out and converted to mixed colors.  What do you think?

![screenshot from 2017-12-07 22-29-12](https://user-images.githubusercontent.com/563334/33749981-f65091d2-db9e-11e7-8eee-a3fde566c576.png)
![screenshot from 2017-12-07 22-26-47](https://user-images.githubusercontent.com/563334/33749984-fb2339da-db9e-11e7-81ec-b8c991b92c00.png)
![screenshot from 2017-12-07 22-33-26](https://user-images.githubusercontent.com/563334/33749987-fe07b91e-db9e-11e7-8b91-e88d1db3acdd.png)
![screenshot from 2017-12-07 22-32-16](https://user-images.githubusercontent.com/563334/33749988-001d53d0-db9f-11e7-82bd-495adbdf6b7f.png)
