### ISSUE TITLE
Clip response force geometries to department jurisdiction

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#426]
Additionally, in order to get a % coverage by structure hazard level for the department, we'd need to clip the response force coverage by the department's jurisdiction and then compute a % of structures covered vs the entire jurisdiction by structure hazard level.  One idea to display the % coverage would be to render the % inside the bars of the parcel counts graph.

**Comment by ssontag55** [comment]
This is now being clipped by the census_owned_geom field and percentage generated

**Comment by meilinger** [comment]
👍
