### ISSUE TITLE
Conditional 42+/38+ effective force for high hazard structures

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#427]
Based on the EMS transport support, the 42+ _could_ be 38+ staffing for high hazard structures.  If the department provides EMS transport, at least 42+ staff are required to be considered effective; however, if a department does **NOT** provide EMS transport then 38+ staff is considered effective for high hazard structures.  The travel time does not change and this only affects high hazard structure coverages.

Either we need to capture "Do you provide EMS transport?" at a department level or prompt the user displaying the response force to respond to that question when displaying the effective response force coverages.

**Comment by ssontag55** [comment]
How can we find whether there is EMS data? @meilinger

**Comment by ssontag55** [comment]
38+ geometry is being added to the database
