### ISSUE TITLE
Mockup of "Data reviewed/verified" badges

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#430]
In order to add transparency to department administrator sign-offs on data being reviewed, we need to implement a method to have badges/verified statuses for departments (akin to verified Twitter/Facebook accounts).  Not only does this increase confidence in the general viewing public but also places more of the ownership on department administrators to keep information in FireCARES up to date.

Potential badges include:

- Department boundary verified
- Station locations verified
- Station staffing information verified

Over time, badges could lose their value/credibility since data verified in, for example, 2017 could become invalid in 2018 due to factors including stations being moved, annexed jurisdictions, changes in staffing, etc so it might be nice to consider a verification date in the badges and/or have badges expire after a certain amount of time.  If a department has all badges current, then they could potentially be marked as a "verified" department.

Sign-off on specific components would only be done by department administrators and the user signing-off on the correctness of the information would have their information as well as the sign-off date captured for historical reasons.

Output of this task is to create a mockup of the workflow for signing off on the validity of data and badge comps/placement.

**Comment by ssontag55** [comment]
@meilinger @bingles Do you think we want to have a validation page for these in the Tools drop down?

![screenshot from 2018-01-31 18-08-16](https://user-images.githubusercontent.com/563334/35652489-d4b1957e-06b1-11e8-9abb-61d03df7247b.png)

**Comment by ssontag55** [comment]
Do we want to have a badge at the top banner for these three showing whether they have been verified?
![screenshot from 2018-01-31 18-10-10](https://user-images.githubusercontent.com/563334/35652570-33d4060e-06b2-11e8-8961-6348199383cd.png)
Pick some fontawesome icons for it?

**Comment by cweinschenk** [comment]
https://fontawesome.com/icons/fire?style=solid
https://fontawesome.com/icons/check?style=solid

Is is possible to layer font awesome icons?

**Comment by ssontag55** [comment]
@cweinschenk for the badges at the top of the screen?  (verified boundary, stations, staffing)

**Comment by cweinschenk** [comment]
Yea -- like some kind of fire check to show you have your fire data verified.

**Comment by ssontag55** [comment]
Sure, I wasn't sure if we wanted to separate them out - have three different checks

**Comment by cweinschenk** [comment]
what are the three check you were thinking?

**Comment by ssontag55** [comment]
(verified boundary, stations, staffing).  Need a good place for admins to check these off too

**Comment by cweinschenk** [comment]
maybe we have one icon on the page to indicate verified but from that drop down there is a option for verification which takes admins to a page where they can toggle the three categories. thoughts on keeping a log of who verifies just in case we need to go back to it at some point?

**Comment by ssontag55** [comment]
Could do something like this:
![admins](https://user-images.githubusercontent.com/563334/35660329-6699c1e2-06d9-11e8-9665-3a5a3dcfcb3f.png)
![verfified](https://user-images.githubusercontent.com/563334/35660332-685007da-06d9-11e8-99f7-b697c599fbbe.png)
![checklist](https://user-images.githubusercontent.com/563334/35660334-69e10f9a-06d9-11e8-8454-335738f5d69a.png)

**Comment by ssontag55** [comment]
@bingles any thoughts on the look of this?

**Comment by bingles** [comment]
@ssontag55 I think it looks pretty good. I have a quick question and a couple of suggestions...will ping you.

**Comment by ssontag55** [comment]
@meilinger @bingles How's this look? Only admins will be able to click on the ckeckbox to verify.

![screenshot from 2018-02-02 23-42-28](https://user-images.githubusercontent.com/563334/35768819-de2ee26c-08cf-11e8-825d-76a09dbb2574.png)
![screenshot from 2018-02-02 23-43-07](https://user-images.githubusercontent.com/563334/35768821-e0bc9538-08cf-11e8-9965-9719449f15a6.png)

**Comment by garnertb** [comment]
Is there a way we can get the status across with just a badge? I personally
don't like the text.  Also, how do you all feel about removing the drop
down and having a separate view for this and other data quality
information?

**Comment by ssontag55** [comment]
Could have checks and clicking on it would take you to the data quality/verification page.  For only admins right?

![screenshot from 2018-02-03 11-52-06](https://user-images.githubusercontent.com/563334/35769426-c2cf92ec-08d8-11e8-8a5f-e8bc6982a299.png)

**Comment by garnertb** [comment]
I was thinking just one icon to show the verification status.

**Comment by ssontag55** [comment]
@bingles you have an icon badge for data verification/under review?

**Comment by bingles** [comment]
Hey, @ssontag55 I am thinking this would be better served simply as an indicator/icon for a verified status. The more I think about it and see options appear in the banner area next to FDID, I become worried that it feels "too forced" in that area and takes away from the use of white space that has been established. 

What if we tried something a little more like what @meilinger mentioned in the initial comment, akin to Twitter. It is an established convention and would work quite well for us IMO. Clicking on the icon would lead you to a separate view as @garnertb mentioned.

What does everyone think about something like below?
![badge](https://user-images.githubusercontent.com/636170/35897356-cde601d0-0b8e-11e8-8062-c0b90f3ffeec.png)

**Comment by ssontag55** [comment]
You can check out the data eval page if you are an admin: https://test.firecares.org/departments/75500/settings/data-validation
