### ISSUE TITLE
Add active wildfires layer to department detail page

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#431]
- Use the https://wildfire.cr.usgs.gov/arcgis/rest/services/geomac_fires/FeatureServer/3/query endpoint for displaying active fires are reported by USGS' MODIS
- Add to layer switcher
- Choose a stylization for this layer that'll fit into the current department detail page map

**Comment by ssontag55** [comment]
![image](https://user-images.githubusercontent.com/563334/33736859-33e038c8-db62-11e7-9ffc-869e7cd4f11c.png)

should we do a legend on the map @meilinger

**Comment by ssontag55** [comment]
![screenshot from 2017-12-08 00-01-16](https://user-images.githubusercontent.com/563334/33751737-ee6e4c32-dbaa-11e7-925a-2601e8b8318b.png)  What do you think of this @meilinger

**Comment by meilinger** [comment]
@ssontag55 i think that the symbology is good, we'll probably want to have 3 layers for these based on the category of the fire (active, last 12-24 hr, last 24-48 hr)

**Comment by meilinger** [comment]
this was deployed to production
