### ISSUE TITLE
Load CENSUS populations into NFIRS

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#435]
In order to be able to automatically update department populations to ensure better accuracy in population attributes for fire departments in FireCARES, we'll need to have population data associated with each census tract in the NFIRS database.

**Comment by ssontag55** [comment]
@meilinger I can do this easier, should we load census tracts with no housing/populations?

**Comment by ssontag55** [comment]
The census table with population blocks is in NFIRS table: census2010_blocks_withpop
