### ISSUE TITLE
Duplicate weather warnings?

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#451]
Seeing duplicate weather warnings in multiple departments.  As an example: https://firecares.org/departments/91164/orland-fire-protection-district .  I'm not sure if this is a gap in my understanding or a real bug, @ssontag55 could you confirm?

**Comment by ssontag55** [comment]
@meilinger I spent a bit of time on this and it is tricky (and messy).  The warning id's are different meaning that anything else could be different (boundary, severity, issue date, expiration date).
Your example looks like the only difference is the issuing date for the warnings:
https://firecares.org/api/v1/weather-warning/?department=91164 (time sensitive) 

Maybe we can dissolve on URL?

**Comment by ssontag55** [comment]
Let's dissolve by url on the front end so that only one warning shows for each url.  The actual unique warning is still stored in the db

**Comment by ssontag55** [comment]
#454 Both updated for less obtrusive weather lists
