### ISSUE TITLE
Effective Response Force

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#453]
I want to start by saying these are awesome. A couple things that would make them immensely more useful:
1. Allow users to turn on and off the different hazard levels as it hard to see with them on top. Whether this is done with radio button below of the charts become clickable. Showing all three at once is really hard to use and if a user wanted to print it won't be really useful.
2. Allow users to select the coverage standard they want. 1710 is only for career departments and not all career departments even follow it. Allowing the time and number to be a variable for users would be huge.
3. Can we append to the parcel database if that parcel what the first due time would be that parcel -- could be really powerful -- maybe toooo powerful.

**Comment by cweinschenk** [comment]
4. Can we create staffing profiles - would need to assign profiles via the station pages -- be for exploring the response capabilities that could be powerful.

**Comment by ssontag55** [comment]
@cweinschenk I think the plan was to allow some users to re-run model dynamically.  It can take a while to run with more complex departments so we're working on a way to do this.  Would the staffing profiles go into this dynamic model run?  

Re:3,  how would we "append to the parcel database of that parcel"

**Comment by cweinschenk** [comment]
I am imagine it might be real time, but we should know who submits to run based on login session so we could run it and then just email when complete. I am sure y'all have thought about that already.

So right now you present an overview table of which parcels of which type fill into first due responses or ERF areas. So at least from a first due perspective we know which parcels can be responded to in 4 minutes or less of travel time. That _could_ be a feature on the parcel popup if we wanted to. Just would require appending the results from these calcs to the core logic parcel database.

**Comment by ssontag55** [comment]
Re: (1.  You can now highlight the chart and it will toggle on and off layers on the map to better see them:
https://test.firecares.org/departments/75500

It seemed like the a better work flow rather than adding more layers to long list of layers.  Comments welcome

**Comment by meilinger** [comment]
@ssontag55 is this wrapped up?
