### ISSUE TITLE
Weather Display

### ISSUE THREAD

**Issue by cweinschenk** [FireCARES/firecares#454]
I really like the weather feature and having this data to link to future data is really important. The challenge I have is pretty much all winter long every northern department is lit up red to the point where I don't even bother looking. Can we do something like only display a weather warning as "on" during a page load if that weather warning is related to red flag as in don't do any outside burning because the wildfire risk is high. Otherwise the weather is off and users can toggle on if they'd like. I doubt anyone is going to firecares for freeze warnings or small craft warnings.

**Comment by ssontag55** [comment]
@cweinschenk Red Flag and Wind might be appropriate?  We can default the layer off if there are these warnings, should we remove the warning header at the top of the page at load or leave that and just turn off map layer?

**Comment by cweinschenk** [comment]
Red flag and wind. Wind is definitely important! Good catch. Hmm good question. Lets go with just the filter on which types trigger on/off for now before messing with anything else. I think the warning bar and layers are good and with less frequency will be more impactful.

**Comment by ssontag55** [comment]
Should we still show the other warnings in the list or filter them out?  We can still load to the database, just filter the list out on the site for now?

**Comment by cweinschenk** [comment]
Sorry, I thought I replied to this. I did in my head but github isn't that smart yet. I was thinking we should still show them if a user clicks on the radio button, but unless it is red flag or wind, they wouldn't auto turn on.
