### ISSUE TITLE
Missing 2015 heatmap fires

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#455]
@ssontag55 did you re-run the CSV heatmap generation for 2015?

@cweinschenk noticed missing heatmap fires for https://firecares.org/departments/85817/kirkland-fire-department, but this appears to be more widespread than just this department

**Comment by ssontag55** [comment]
@cweinschenk @meilinger Looks like 2013/2014 was missing before I re-ran the data:
https://s3.amazonaws.com/firecares-test/2014/85817-building-fires.csv

Still no geolocation matching data for 2015.

**Comment by meilinger** [comment]
@ssontag55 looks like _some_ of the heatmap data is in place (eg. https://firecares.org/departments/75500/boston-fire-department), but is missing for quite a few:

Few examples of missing heatmap data:

- [ ] https://firecares.org/departments/79277/dallas-fire-department
- [ ] https://firecares.org/departments/77379/chicago-fire-department

**Comment by meilinger** [comment]
@ssontag55 any luck on finding the cause for the discrepancies?

**Comment by ssontag55** [comment]
Reloaded incident data for 2015 and now see more lat/long matching for departments
