### ISSUE TITLE
ERF response areas and aggregations schedule

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#456]
After a department admin updates their staffing information for a station we'll need to re-run the ERF processes to capture their new staffing information.  The challenge will be figuring out how to handle this as multiple stations could be updated and cause unnecessary DB/service thrashing.  Do we queue up updates and run once on a daily schedule (or another timespan) for departments that had staffing table updates?  Open to suggestions.

**Comment by cweinschenk** [comment]
Can we allow the department admin to click a radio button to allow for a ERF update within 24 hours and if the ERF button is hit a couple times within a time window of first click that still counts as one update request.

**Comment by ssontag55** [comment]
@meilinger I think Celery can manage this.  Django signals are blocking so I've left out the erf update on department change/edit.  Can we have a celery task run the update and it should handle multiple updates?

**Comment by meilinger** [comment]
Yeah, celery task would be the way to go...tricky thing will be removing/preventing duplicate task calls for that specific department over a certain timeframe (24 hours sounds good) so that we don't queue up 100s of the same task call when editing station staffing information.
