### ISSUE TITLE
Get current count of departments with staffing information populated

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#466]
Need to send to Lori in order to support marketing effort.  Should contain staffing counts for each department as well as total count/% of departments staffed.  Due 2/28/2018

**Comment by ssontag55** [comment]
[data-1519756151985.txt](https://github.com/FireCARES/firecares/files/1764212/data-1519756151985.txt)

**Comment by meilinger** [comment]
@ssontag55 thanks!
