### ISSUE TITLE
TTFB increase

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#473]
Looks like our TTFB has almost tripled over the past few days for health checks.  No code updates deployed to production since 2/14.

<img width="869" alt="uptime_reports" src="https://user-images.githubusercontent.com/197163/37525732-a069c9c8-28fb-11e8-919e-d2919a84830d.png">

**Comment by ssontag55** [comment]
this might be with me loading over half a billion records for ems.  And running update queries.

**Comment by meilinger** [comment]
I tried connecting to the prod DB from my local dev box and things were running as expected < 500ms avg time so DB is probably not the issue.

**Comment by meilinger** [comment]
Latest deployment fixed this, could be:

- gunicorn needing to be recycled
- Much less likely, but nginx possibly needing a reload
