### ISSUE TITLE
Service area click to highlight

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#474]
Need to have the same ability as the ERF to persist the highlighted area on click.  Apply to department level as well as station-level service areas if possible.

**Comment by meilinger** [comment]
Also, we should probably look into ways to prevent obfuscation of the existing map when the 0-4/4-6/etc popups display, one option (per @cweinschenk ) was to display the information below the map.

**Comment by ssontag55** [comment]
We can put it in the notification bar on the lower left hand side of the map, and color it differently.  What do you think @cweinschenk @meilinger

**Comment by cweinschenk** [comment]
I like that.
