### ISSUE TITLE
Add spam filter on non-authenticated message submissions

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#505]
Getting quite a bit of spam recently that is already semi-prevented via captcha, but we need to add an additional layer of spam prevention.  Akismet has worked well in the past to circumvent these issues.

**Comment by meilinger** [comment]
see https://github.com/FireCARES/firecares/tree/feature/spam-filtering

**Comment by zunware** [comment]
Tested with spam and legit messages, detection worked good.

<img width="721" alt="Screen Shot 2019-03-18 at 1 27 07 PM" src="https://user-images.githubusercontent.com/4162671/54557908-e5694100-4981-11e9-80ad-54fc0c83f3b2.png">

**Comment by zunware** [comment]
Closed with #509
