### ISSUE TITLE
History graph shows NaN for some departments

### ISSUE THREAD

**Issue by larskendall** [FireCARES/firecares#532]
So far I've only noticed this with San Antonio, TX when showing EMS data. Oddly, the aster charts (Month/Day/Hour) work fine, so the problem seems to be specific to the History bar chart.

<img width="805" alt="Screen Shot 2019-11-22 at 9 06 00 PM" src="https://user-images.githubusercontent.com/3220897/69473690-f4ec2580-0d6b-11ea-8941-67aba2474fff.png">

**Comment by meilinger** [comment]
fixed via 7a7fbd8cc41b88378c7f4b8f022f11bb89c59ea5
