### ISSUE TITLE
FOUC (Flash of unstyled content) issues on department/firestation pages

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#55]
Putting stylesheets in the head should help.

**Comment by garnertb** [comment]
@meilinger, strong work here.

**Comment by meilinger** [comment]
@garnertb Thanks!  If we run into more issues, I'm sure there's more that could be done...this was just a start.

**Comment by garnertb** [comment]
@meilinger, understood.  I don't see any JS errors or FOUCS right now so I'm happy.
