### ISSUE TITLE
Map inner shadow mis-aligned

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#57]
![firecares_ _the_community_assessment_response_evaluation_system](https://cloud.githubusercontent.com/assets/197163/11316230/fec0130e-8fc6-11e5-99b7-6e108153ae5d.jpg)

On homepage.

**Comment by garnertb** [comment]
Note, that the same map classes are used in the department detail page but in that implementation it works.  Make sure that fixing the inner-shadow on the home page doesn't break it.

**Comment by meilinger** [comment]
Was sure to make the selector specific to the homepage (eg. using a "featured" section) and double-checked the other maps to be sure.
