### ISSUE TITLE
Station paginator wrapping issues

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#58]
For departments that have a lot of stations, see /departments/81472/fire-department-city-of-new-york-fdny
![community_assessment__fire_department_city_of_new_york__fdny_](https://cloud.githubusercontent.com/assets/197163/11316335/6eb2ac06-8fc9-11e5-8eed-efe291019d18.jpg)

**Comment by meilinger** [comment]
This might need to be an abbreviated paginator vs full => http://stackoverflow.com/questions/25838135/how-to-make-responsive-bootstrap-3-pagination

**Comment by Coop56** [comment]
I'll take care of this right after I finish Issue #83.

**Comment by Coop56** [comment]
Commit and pull request sent on this.

**Comment by meilinger** [comment]
closed via #88
