### ISSUE TITLE
Bad search page tile wrapping when department is missing thumbnail

### ISSUE THREAD

**Issue by meilinger** [FireCARES/firecares#62]
![search_for_a_community_ _firecares](https://cloud.githubusercontent.com/assets/197163/11356749/6dfb7dc4-9226-11e5-9ef8-65000f9fa295.jpg)

**Comment by meilinger** [comment]
BTW, the broken image: https://s3.amazonaws.com/firecares-static/department-thumbnails/us-mo-mid-county-fire-protection-district.jpg returns a 403 (Forbidden).

**Comment by garnertb** [comment]
FYI: https://s3.amazonaws.com/firecares-static/department-thumbnails/us-mo-mid-county-fire-protection-district.jpg is fixed.

**Comment by garnertb** [comment]
May want to script out some logic to see if any others are broken.  @meilinger: Feel free to do so if you have cycles.

**Comment by meilinger** [comment]
@garnertb I was thinking the exact same thing, an out-of-band script should work fairly well.

**Comment by meilinger** [comment]
@garnertb This *should* be good, there were only 38 bad thumbnails out of over 27000...see email for list w/ department id.

**Comment by garnertb** [comment]
I re-ran the create thumbnail logic on those 38 so we're good.  Thanks!
