### ISSUE TITLE
Order stations based on station number vs string on department detail page.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#69]

**Comment by meilinger** [comment]
On this department detail page?
![community_assessment__fairfax_county_fire_and_rescue_department](https://cloud.githubusercontent.com/assets/197163/11581041/3b039e12-9a03-11e5-9c90-04f9f16dbb93.jpg)

**Comment by garnertb** [comment]
Yep, thats the one. I re-worded the issue.

**Comment by meilinger** [comment]
I wasn't sure on the heuristics to use for determining the `station_number` for a FireStation, so simply stuck w/ numbers that followed "Station", should the same apply for stations that use "Engine", "District", "Company", "Department" or "Substation"?  There are ~3100 out of ~3460 stations that contain a number of some sort that fit into one of those 5 conditions.

**Comment by meilinger** [comment]
@garnertb No reverse migration on this one, but we should be covered.
