### ISSUE TITLE
Implement the DIST Score and Protected Population filters on the search page.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#7]
<img width="275" alt="screen shot 2015-08-01 at 11 03 03 am" src="https://cloud.githubusercontent.com/assets/1141646/9022268/335a99c2-383d-11e5-8ef3-e5e64c6769c3.png">

**Comment by acengic** [comment]
I'm looking at this issue #7.   
Test case would be to filter on "diet score” range and/or “Protected Population” range (60:120)

Did you write directives for gauges, module.directive(‘barGauge’ ...

Did you make

**Comment by garnertb** [comment]
Yes, I wrote the directives for the gauges.  In order to keep the issues clean, please only reply to github issue threads with comments or questions that are relevant to that particular thread.  If you have a general question, please email me directly.

**Comment by meilinger** [comment]
Does this need to be worked?  From what I can tell it appears to be working ok.

**Comment by garnertb** [comment]
Looks like the only thing left open is humanizing the population numbers
(ie "3201720 : 9818610" should be 3,201,720 : 9,818,610).

On Fri, Nov 20, 2015 at 9:46 PM, Joe Meilinger <notifications@github.com>
wrote:

> Does this need to be worked? From what I can tell it appears to be working
> ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FireCARES/firecares/issues/7#issuecomment-158578758>.
>



-- 
-Tyler Garner
