### ISSUE TITLE
Add a "Media" section.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#83]
Embed this video:
https://www.youtube.com/watch?v=dJK_jIUz9Ok

**Comment by garnertb** [comment]
@meilinger, do you have any cycles to help with this?

**Comment by meilinger** [comment]
@garnertb yep, assuming that we'd just want to use the same minimalistic template as the http://firecares.org/community-risk page? or should this be embedded in a sidebar or something along those lines?

**Comment by garnertb** [comment]
Yes, the minimalistic page is fine.  If you can spruce it up all even better, but thats acceptable.

**Comment by meilinger** [comment]
Need this today or w/in the next 3-4 days?  Just balancing priorities.

**Comment by garnertb** [comment]
Within the next 3-4 is fine.

**Comment by garnertb** [comment]
@meilinger any chance you could switch to https://github.com/FireCARES/firecares/issues/82 instead of this one?

**Comment by meilinger** [comment]
Will do

**Comment by meilinger** [comment]
@Coop56 see https://github.com/FireCARES/firecares/tree/83-add-media-section for a basic start, probably needs some lockdown on the CKEditor for supported HTML elements, template is just copied at this point

**Comment by Coop56** [comment]
Commits done and pull request sent.
