### ISSUE TITLE
Update Properties Search

### ISSUE THREAD

**Issue by Coop56** [FireCARES/firecares#90]
There's a lot of places where there seems to be some remnant code left over that allows users to search properties that don't exist in our context.  Need to go through and remove all mentions of this code.

**Comment by Coop56** [comment]
Instead of removing it - we're going to change it to a department search.  Working on this next.

**Comment by Coop56** [comment]
I ran into some errors trying to get the search to work on all pages - so for now I've just removed property search from all pages as that still looks better than having it there.  I'm going to knock out some other tasks and then try to implement department search on all pages again later.

**Comment by larskendall** [comment]
Department search should be working on all pages on mobile now.
